version: "3.7"


services:
  mysql:
    restart: always
    image: mysql:5.7.38
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./env/.env
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=mysqluser
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - "${MYSQL_PORT}"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./docker/init/mysql:/docker-entrypoint-initdb.d
      - ./docker/volumes/mysql:/var/lib/mysql
    networks:
      - net

networks:
  net: null
